<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ManageRamen.aspx.cs" Inherits="dummyRamen.View.ManageRamen" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:GridView ID="RamenGV" runat="server" AutoGenerateDeleteButton="true" OnRowDeleting="RamenGV_RowDeleting"></asp:GridView>
            <br /><br />
            <asp:Button ID="btn_add" runat="server" Text="Add" OnClick="btn_add_Click" />
            <asp:Button ID="btn_edit" runat="server" Text="Edit Ramen" OnClick="btn_edit_Click"  />
        </div>
    </form>
</body>
</html>
